[tool.poetry]
name = "baca2"
version = "0.1.0"
description = ""
authors = ["BaCa2 Team"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
django = "^4.1.3"
psycopg2-binary = "^2.9.5"
django-allauth = "^0.51.0"
django-extensions = "^3.2.1"
django-dbbackup = "^4.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
