# Generated by Django 4.2.5 on 2023-10-02 16:39

from django.db import migrations, models
import django.db.models.deletion
import main.models
import package.models
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(null=True)),
                ('deadline_date', models.DateTimeField()),
                ('reveal_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_instance_id', models.BigIntegerField(validators=[package.models.PackageInstance.exists])),
                ('task_name', models.CharField(max_length=1023)),
                ('judging_mode', models.CharField(choices=[('LIN', 'Linear'), ('UNA', 'Unanimous')], default='LIN', max_length=3)),
                ('points', models.FloatField()),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.round')),
            ],
        ),
        migrations.CreateModel(
            name='TestSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.task')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=255)),
                ('test_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.testset')),
            ],
        ),
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('source_code', models.FileField(upload_to=pathlib.PureWindowsPath('C:/Users/Krzysztof/Desktop/stuff/projects/baca2_project/baca2/BaCa2/submits'))),
                ('usr', models.BigIntegerField(validators=[main.models.User.exists])),
                ('final_score', models.FloatField(default=-1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.task')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PND', 'Pending'), ('OK', 'Test accepted'), ('ANS', 'Wrong answer'), ('RTE', 'Runtime error'), ('MEM', 'Memory exceeded'), ('TLE', 'Time limit exceeded'), ('CME', 'Compilation error'), ('EXT', 'Unknown extension'), ('INT', 'Internal error')], default='PND', max_length=3)),
                ('submit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.submit')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.test')),
            ],
        ),
    ]
