# Generated by Django 4.1.3 on 2022-12-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='judging_mode',
            field=models.CharField(choices=[('LIN', 'Linear'), ('UNA', 'Unanimous')], default='LIN', max_length=3),
        ),
    ]
