# Generated by Django 4.2.6 on 2023-10-23 15:21

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_result_runtime_memory_result_time_cpu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='source_code',
            field=models.FilePathField(path=pathlib.PureWindowsPath('C:/Users/user/Desktop/stuff/projects/baca2_project/baca2/BaCa2/submits')),
        ),
    ]
