# Generated by Django 4.1.3 on 2022-12-14 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_task_judging_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submit',
            old_name='user',
            new_name='usr',
        ),
    ]
