# Generated by Django 5.0.6 on 2024-06-11 12:39

from django.db import migrations, models

import course.models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='usr',
            field=models.BigIntegerField(db_index=True, validators=[course.models.SubmitManager.user_exists_validator]),
        ),
    ]
