# Generated by Django 4.1.3 on 2022-12-14 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_rename_user_submit_usr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='source_code',
            field=models.FileField(upload_to='./submits'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.task'),
        ),
    ]
