# Generated by Django 4.1.3 on 2022-12-18 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_submit_source_code_alter_submit_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='task_set',
            new_name='test_set',
        ),
        migrations.RemoveField(
            model_name='test',
            name='task',
        ),
        migrations.AddField(
            model_name='testset',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='course.task'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submit',
            name='source_code',
            field=models.FileField(upload_to='./BaCa2/course/submits'),
        ),
    ]
