# Generated by Django 4.1.3 on 2022-12-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_rename_task_set_test_test_set_remove_test_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='points',
            field=models.FloatField(default=9),
            preserve_default=False,
        ),
    ]
