# Generated by Django 4.1.3 on 2022-12-19 21:16

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_task_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='source_code',
            field=models.FileField(upload_to=pathlib.PureWindowsPath('Q:/Dokumenty/!Studia/!Projects/BaCa2/BaCa2/submits')),
        ),
    ]
