# Generated by Django 4.1.5 on 2023-01-26 22:18

from django.db import migrations, models
import main.models
import package.models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_submit_source_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='package_instance',
        ),
        migrations.AddField(
            model_name='task',
            name='package_instance_id',
            field=models.BigIntegerField(default=None, validators=[package.models.PackageInstance.exists]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submit',
            name='source_code',
            field=models.FileField(upload_to=pathlib.PurePosixPath('/home/zyndram/Dokumenty/BaCa2/BaCa2/submits')),
        ),
        migrations.AlterField(
            model_name='submit',
            name='usr',
            field=models.BigIntegerField(validators=[main.models.User.exists]),
        ),
    ]
