# Generated by Django 4.1.3 on 2022-12-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_submit_source_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='usr',
            field=models.FloatField(),
        ),
    ]
