# Generated by Django 4.1.5 on 2023-01-27 02:14

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_remove_task_package_instance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='source_code',
            field=models.FileField(upload_to=pathlib.PureWindowsPath('Q:/Dokumenty/!Studia/!Projects/BaCa2/BaCa2/submits')),
        ),
    ]
