# Generated by Django 4.1.3 on 2023-01-06 18:33

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_submit_usr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='source_code',
            field=models.FileField(upload_to=pathlib.PureWindowsPath('Q:/Dokumenty/!Studia/!Projekty/BaCa2/BaCa2/submits')),
        ),
    ]
