# Generated by Django 4.1.3 on 2023-01-10 18:07

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_submit_usr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='usr',
            field=models.BigIntegerField(validators=[main.models.User.exists]),
        ),
    ]
