# Generated by Django 4.2.4 on 2023-08-17 10:49

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_submit_source_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='source_code',
            field=models.FileField(upload_to=pathlib.PurePosixPath('/Users/mati/Documents/BaCa2/BaCa2/submits')),
        ),
    ]
