# Generated by Django 4.1.3 on 2023-01-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_submit_usr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='package_instance',
        ),
        migrations.AddField(
            model_name='task',
            name='package_instance_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
