# Generated by Django 4.2.3 on 2023-08-21 15:06

from django.db import migrations, models
import package.models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_remove_task_package_instance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='source_code',
            field=models.FileField(upload_to=pathlib.PureWindowsPath('C:/Users/Krzysztof/Desktop/stuff/projects/baca2_project/baca2/BaCa2/submits')),
        ),
        migrations.AlterField(
            model_name='task',
            name='package_instance_id',
            field=models.BigIntegerField(validators=[package.models.PackageInstance.exists]),
        ),
    ]
