# Generated by Django 4.2.5 on 2023-09-19 11:13

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_submit_source_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='source_code',
            field=models.FilePathField(path=pathlib.PurePosixPath('/home/zyndram/Dokumenty/BaCa2/BaCa2/submits')),
        ),
    ]
