# Generated by Django 4.2.5 on 2023-10-02 16:39

import baca2PackageManager.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit', models.CharField(max_length=2047)),
            ],
        ),
        migrations.CreateModel(
            name='PackageSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=511, validators=[baca2PackageManager.validators.isStr])),
            ],
        ),
        migrations.CreateModel(
            name='PackageInstanceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.packageinstance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='packageinstance',
            name='package_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.packagesource'),
        ),
    ]
