# Generated by Django 5.0.4 on 2024-04-22 18:40

import pathlib

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import baca2PackageManager.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('commit', models.CharField(max_length=2047)),
                ('pdf_docs',
                 models.FilePathField(blank=True, default=None, max_length=2047, null=True,
                                      path=pathlib.PurePosixPath(
                                          '/home/www/BaCa2/BaCa2/task_descriptions'))),
            ],
        ),
        migrations.CreateModel(
            name='PackageSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('name', models.CharField(max_length=511,
                                          validators=[baca2PackageManager.validators.isStr])),
            ],
        ),
        migrations.CreateModel(
            name='PackageInstanceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('name', models.CharField(max_length=511)),
                ('path', models.FilePathField(max_length=2047, path=pathlib.PurePosixPath(
                    '/home/www/BaCa2/BaCa2/attachments'))),
                ('package_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                       to='package.packageinstance')),
            ],
        ),
        migrations.CreateModel(
            name='PackageInstanceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('package_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                       to='package.packageinstance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='packageinstance',
            name='package_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='package.packagesource'),
        ),
    ]
