# Generated by Django 5.0.4 on 2024-04-24 15:43

import pathlib

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageinstance',
            name='pdf_docs',
            field=models.FilePathField(blank=True, default=None, max_length=2047, null=True,
                                       path=pathlib.PureWindowsPath(
                                           'Q:/Dokumenty/!Studia/!Projects/BaCa2/BaCa2/task_descriptions')),
        ),
        migrations.AlterField(
            model_name='packageinstanceattachment',
            name='path',
            field=models.FilePathField(max_length=2047, path=pathlib.PureWindowsPath(
                'Q:/Dokumenty/!Studia/!Projects/BaCa2/BaCa2/attachments')),
        ),
    ]
