CREATE ROLE root WITH
    LOGIN
    SUPERUSER
	CREATEDB
	CREATEROLE
	INHERIT
	REPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'BaCa2root';
GRANT postgres TO root WITH ADMIN OPTION;
COMMENT ON ROLE root IS 'root db user for db management purposes';
