# Generated by Django 4.2.5 on 2023-10-07 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_settings',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='main.settings'),
        ),
    ]
