# Generated by Django 4.1.3 on 2023-01-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_course_groupcourse_usercourse_delete_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='db_name',
            field=models.CharField(default='default', max_length=127),
        ),
    ]
