# Generated by Django 5.0.4 on 2024-06-03 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
    ]
