# Generated by Django 4.2.6 on 2023-10-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_user_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'permissions': [('view_course_member', 'Can view course members'), ('add_course_member', 'Can add course members'), ('delete_course_member', 'Can delete course members'), ('change_course_member_role', "Can change course member's role"), ('view_course_role', 'Can view course role'), ('edit_course_role', 'Can edit course role'), ('add_course_role', 'Can add course role'), ('delete_course_role', 'Can delete course role')]},
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
