# Generated by Django 4.2.6 on 2023-10-23 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_course_options_remove_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(auto_now_add=True, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_settings',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='main.settings', verbose_name='user settings'),
        ),
    ]
