# Generated by Django 4.2.3 on 2023-08-21 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_course_db_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='dark', max_length=255, verbose_name='UI theme')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_settings',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.settings'),
            preserve_default=False,
        ),
    ]
