# Generated by Django 4.2.3 on 2023-08-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_settings_user_user_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='db_name',
            field=models.CharField(max_length=127, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_name',
            field=models.CharField(max_length=31, unique=True),
        ),
    ]
