# Generated by Django 4.2.6 on 2023-10-24 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0005_alter_user_date_joined_alter_user_user_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='preset name')),
                ('public', models.BooleanField(default=True, help_text='Indicates whether the preset is public. Public presets can be used by all users, private presets can only be used by their creator or other users given access.', verbose_name='preset is public')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission', verbose_name='preset permissions')),
            ],
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'permissions': [('view_course_member', 'Can view course members'), ('add_course_member', 'Can add course members'), ('remove_course_member', 'Can remove course members'), ('change_course_member_role', "Can change course member's role"), ('add_course_admin', 'Can add course admins'), ('view_course_role', 'Can view course role'), ('edit_course_role', 'Can edit course role'), ('add_course_role', 'Can add course role'), ('delete_course_role', 'Can delete course role'), ('view_course_tasks', 'Can view tasks in the course'), ('add_course_tasks', 'Can add tasks to the course'), ('edit_course_tasks', 'Can edit tasks in the course'), ('delete_course_tasks', 'Can delete tasks from the course'), ('add_course_rounds', 'Can add rounds to the course'), ('edit_course_rounds', 'Can edit rounds in the course'), ('delete_course_rounds', 'Can delete rounds from the course')]},
        ),
        migrations.CreateModel(
            name='RolePresetUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_preset_users', to='main.rolepreset', verbose_name='preset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_role_presets', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='role name')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_roles', to='main.course', verbose_name='course')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission', verbose_name='role permissions')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='The course roles this user has been assigned to.', related_name='user_set', related_query_name='user', to='main.role', verbose_name='roles'),
        ),
    ]
