# Generated by Django 4.2.4 on 2023-10-02 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0006_alter_course_db_name_alter_course_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='db_name',
        ),
        migrations.AddField(
            model_name='course',
            name='USOS_course_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Subject code'),
        ),
        migrations.AddField(
            model_name='course',
            name='USOS_term_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Term code'),
        ),
        migrations.AddField(
            model_name='course',
            name='admin_role',
            field=models.ForeignKey(default=1, limit_choices_to={'groupcourse__course': None}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auth.group', verbose_name='admin role'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='default_role',
            field=models.ForeignKey(default=1, limit_choices_to={'groupcourse__course': None}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='auth.group', verbose_name='default role'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, verbose_name='course name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='course short name'),
        ),
        migrations.AlterField(
            model_name='groupcourse',
            name='group',
            field=models.ForeignKey(limit_choices_to={'groupcourse': None}, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.DeleteModel(
            name='UserCourse',
        ),
    ]
