# Generated by Django 4.2.6 on 2023-10-24 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rolepreset_alter_course_options_rolepresetuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_roles', to='main.course', verbose_name='course'),
        ),
    ]
