# Generated by Django 4.2.6 on 2023-10-25 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_role_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_set', to='main.course', verbose_name='course'),
        ),
        migrations.DeleteModel(
            name='GroupCourse',
        ),
    ]
