# Generated by Django 4.2.6 on 2023-10-25 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0008_alter_role_course_delete_groupcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepreset',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_role_presets', to=settings.AUTH_USER_MODEL, verbose_name='preset creator'),
        ),
        migrations.AlterField(
            model_name='course',
            name='admin_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='main.role', verbose_name='admin role'),
        ),
        migrations.AlterField(
            model_name='course',
            name='default_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='main.role', verbose_name='default role'),
        ),
        migrations.AlterField(
            model_name='rolepreset',
            name='permissions',
            field=models.ManyToManyField(blank=True, null=True, to='auth.permission', verbose_name='preset permissions'),
        ),
    ]
