# Generated by Django 4.2.6 on 2023-10-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0009_rolepreset_creator_alter_course_admin_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepreset',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission', verbose_name='preset permissions'),
        ),
    ]
