# Generated by Django 4.2.6 on 2023-10-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_course_admin_role_alter_course_default_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='short_name',
            field=models.CharField(max_length=40, unique=True, verbose_name='course short name'),
        ),
    ]
