apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: apache
spec:
  selector:
    matchLabels:
      app: test
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: ubuntu:latest
          command: [ "/bin/sh", "-c", "apt update -y && apt install -y apache2 && service apache2 start && tail -f /dev/null" ]
          ports:
            - name: http
              containerPort: 80
          #            - name: https
          #              containerPort: 443
          env:
            - name: DEBIAN_FRONTEND
              value: noninteractive
---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
  selector:
    app: test
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30080
      targetPort: http
  externalIPs:
    - 149.156.65.133
#    - protocol: TCP
#      port: 443
#      targetPort: https
