name: Docs
on: [push, pull_request, workflow_dispatch]
jobs:
  docs:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres:latest
        env:
          # must specify password for PG Docker container image, see: https://registry.hub.docker.com/_/postgres?tab=description&page=1&name=10
          POSTGRES_PASSWORD: BaCa2root
          POSTGRES_USER: root
          POSTGRES_DB: postgres_db
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install db client
        run: |
          sudo apt-get update
          sudo apt-get install --yes postgresql-client
      - name: Add default project database
        run: sudo psql -h postgres -d postgres_db -U root -c 'CREATE DATABASE baca2db;'
        env:
          PGPASSWORD: BaCa2root
      - name: Create default db user for project
        run: sudo psql -h postgres -d postgres_db -U root -c 'create user baca2 with encrypted password "zaqwsxcde";'
        env:
          PGPASSWORD: BaCa2root
      - name: Grant privileges to default db user
        run: sudo psql -h postgres -d postgres_db -U root -c 'grant all privileges on database baca2db to baca2;'
        env:
          PGPASSWORD: BaCa2root
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme django django-allauth django-extensions django-dbbackup pyyaml psycopg2
      - name: Sphinx build
        run: |
          sphinx-build BaCa2/docs/source BaCa2/docs/build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/
          force_orphan: true