# Generated by Django 4.2.4 on 2023-08-26 20:50

import broker_api.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0004_course_db_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_id', models.BigIntegerField()),
                ('package_path', models.FilePathField(allow_folders=True)),
                ('solution_path', models.FilePathField(allow_folders=True)),
                ('status', models.IntegerField(default=0, verbose_name=broker_api.models.BrokerSubmit.StatusEnum)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
        ),
    ]
