# Generated by Django 4.2.5 on 2023-10-07 13:16

import broker_api.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('package', '0001_initial'),
        ('main', '0003_alter_user_user_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_id', models.BigIntegerField()),
                ('status', models.IntegerField(default=0, verbose_name=broker_api.models.BrokerSubmit.StatusEnum)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('package_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.packageinstance')),
            ],
        ),
    ]
