# Generated by Django 4.2.5 on 2023-09-14 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
        ('broker_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brokersubmit',
            name='package_path',
        ),
        migrations.RemoveField(
            model_name='brokersubmit',
            name='solution_path',
        ),
        migrations.AddField(
            model_name='brokersubmit',
            name='package_instance',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='package.packageinstance'),
            preserve_default=False,
        ),
    ]
