# Generated by Django 5.0.4 on 2024-04-22 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('broker_api', '0001_initial'),
        ('main', '0001_initial'),
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokersubmit',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
        migrations.AddField(
            model_name='brokersubmit',
            name='package_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='package.packageinstance'),
        ),
    ]
